### ISSUE TITLE
Provide ES5 build?

### ISSUE THREAD

**Issue by donmccurdy** [donmccurdy/three-pathfinding#10]
Maybe Rollup, maybe not...

**Comment by johnryork** [comment]
this one has been plaguing me the last couple days. I'm new to npm and pulling my hair out trying to work around this issue. any pointers on how I might manually run the ES5 build myself?

**Comment by donmccurdy** [comment]
The files in [dist/*](https://github.com/donmccurdy/three-pathfinding/tree/master/dist) are already compiled to ES5,  you could include those by copy/paste. Might depend on your build system whether you can grab them with `require('three-pathfinding/dist/three-pathfinding')` or not.
