### ISSUE TITLE
Navigation mesh

### ISSUE THREAD

**Issue by vas4oo** [donmccurdy/three-pathfinding#106]
Can a navigation mesh still be built in blender 2.93 ver?

**Comment by donmccurdy** [comment]
Blender's tools for automatically generating a navmesh were removed with BGE. Any mesh can be used if it has consistent triangle sizes (not too long or thin, or roughly the same size) but you would need to model the mesh to the walkable areas manually.

The tool Blender previously used (Recast Navigation) is open source but takes some work to set up.

**Comment by vas4oo** [comment]
Okay, thank you for your response :)
