### ISSUE TITLE
Not suitable for threejs versions higher than 0.120.0

### ISSUE THREAD

**Issue by 26268zzh** [donmccurdy/three-pathfinding#118]
When I use threejs version higher than 0.120.0 it report an error ：Class constructor Object3D cannot be invoked without 'new'，I guess this is because the project does not have threejs adapted to es6 syntax。I would like to know how to modify the source code。

**Comment by 26268zzh** [comment]
In addition, I am using the three-pathfinding installed by npm. Although it says Update dependency three to v0.135.0 in package.json, it does not run normally.

**Comment by donmccurdy** [comment]
Thanks! This should be fixed by https://github.com/donmccurdy/three-pathfinding/pull/119.

If you need a workaround that doesn't involve imports from source files, this should also work:

```js
import { Pathfinding, PathfindingHelper } from 'three-pathfinding/dist/three-pathfinding.modern.js"
```
