### ISSUE TITLE
Installation documentation

### ISSUE THREAD

**Issue by mimooh** [donmccurdy/three-pathfinding#12]
#Sorry, nodejs is a mystery to me, I cannot figure it out from the docs how to run this thing. After reading external docs (sad it's not in your docs) I went this far:

```
cd three-pathfinding
npm i --save three
npm i --save three-gltf-loader
```

then I create x.js script:

```js
let mesh;

var loader = new THREE.GLTFLoader();
loader.load( 'navmesh.gltf', ({scene}) => {
    scene.traverse((node) => {
        if (node.isMesh) mesh = node;
    });
}, undefined, (e) => {
    console.error(e);
});
```

`nodejs x.js: ReferenceError: THREE is not defined`

So I try with this line first: 

```js
var THREE = require('three')
```

which results in:

```
var loader = new THREE.GLTFLoader();
// TypeError: THREE.GLTFLoader is not a constructor
```

So I google around for "npm GLTFLoader()" and find things which don't work

```
import GLTF2Loader from 'three-gltf-loader'
```

Can you provide the description for the nodejs beginners like me?

**Comment by donmccurdy** [comment]
Hi! Yeah I'll try to write up something with more detail in a few days. Just to check, how are you hoping to use this? Are you using pathfinding in a webpage, or do you want to run it on a server somewhere?

**Comment by mimooh** [comment]
I need a console app, without any visualization, so nodejs as I understand. Your script has a nice interface to recast/detour. Is your engine using recast/detour internals?

**Comment by donmccurdy** [comment]
Hm, I don't know whether GLTFLoader will work in node.js. It depends on what your file contains, e.g. much of the texture handling is browser-specific. The good news is that you can use any loader you want, or create a `THREE.Mesh` directly from raw data. Most of the three.js loaders need to be downloaded from the `examples/js/loaders` folder of three.js and added to your project separately.

This project itself does not use Recast/Detour, but I do use a [CLI version of Recast](https://github.com/but0n/recastCLI.js/) to _create_ navigation meshes, which this project can then use.

**Comment by donmccurdy** [comment]
Actually the easiest way to include a loader would be:

```js
const THREE = global.THREE = require('three');
require('three/examples/js/loaders/GLTFLoader');
const loader = new THREE.GLTFLoader();
// ...
```

If that doesn't work in Node.js, it may be worth trying THREE.OBJLoader too.

**Comment by donmccurdy** [comment]
Added documentation in 070b48c47cff32786f72d6b31b97d8dacc67e5c0.
