### ISSUE TITLE
Navmesh representation

### ISSUE THREAD

**Issue by mimooh** [donmccurdy/three-pathfinding#13]
"This library does not build navigation meshes for you — instead, create a navigation mesh using Blender, Recast (CLI), or another tool."

I'd say that the original Recast writes the output to some binary structure which is more than just geometry. I don't expect it's that easy to just extract the geometry into the .gltf. The question is: are you sure of what you state above, I mean the Recast part? I am not commenting Blender or CLI outputs.

**Comment by donmccurdy** [comment]
Hi! Recast can write to a binary structure, as you mention, and currently this library does not support that. But fortunately Recast can also be used to extract geometry from the navigation mesh and write that to an OBJ. I've been using https://github.com/but0n/recastcli.js to do this in Node.js.

**Comment by mimooh** [comment]
Yes, but I am refering to docs on your site. I would understand that all
3 tools (1.blender, 2.recast(link given), 3.recastcli.js) produce the
input navmesh for your system. But option 2 is untrue.

BTW, recastcli.js is broken currently :(

-- 
Karol Kreński
tel. 517-302-055

**Comment by donmccurdy** [comment]
I'm not aware that https://github.com/recastnavigation/recastnavigation has any one correct output style... it can write the binary navigation mesh, or a tiled navigation mesh, or simple geometry... perhaps using it for geometry is less common? I'd welcome suggestions in the docs if you think the docs could be better — I've tried to be specific (`The library accepts a THREE.Geometry instance`) about the current need for raw geometry.

**Comment by donmccurdy** [comment]
About recastcli I assume you mean this issue? https://github.com/but0n/recastCLI.js/issues/11

FWIW I have a slightly older version of the package published to NPM which works for me:

- https://www.npmjs.com/package/@donmccurdy/recast
- Usage: https://github.com/donmccurdy/aframe-inspector-plugin-recast/blob/master/function.js

**Comment by mimooh** [comment]
> About recastcli I assume you mean this issue? https://github.com/but0n/recastCLI.js/issues/11
Yes.
 
> FWIW I have a slightly older version of the package published to NPM which works for me:
> - https://www.npmjs.com/package/@donmccurdy/recast
> - Usage: https://github.com/donmccurdy/aframe-inspector-plugin-recast/blob/master/function.js
OK, thanks.

**Comment by mimooh** [comment]
I admit I am not competent enough in this matters. This tool
https://github.com/arl/go-detour (based on recast/detour) produces the
binary navmesh and I thought this is the most standard representation.

**Comment by donmccurdy** [comment]
Added more documentation in 070b48c47cff32786f72d6b31b97d8dacc67e5c0.
