### ISSUE TITLE
getClosestNode() Can I get the Node closest follow Y axis

### ISSUE THREAD

**Issue by tranhogdiep** [donmccurdy/three-pathfinding#179]
Hello guys, I making an FPS game with a jump function. When I jump from a high to a low position. GetClosestNode always returns the higher Node. But I want the lower.
![image](https://user-images.githubusercontent.com/24771572/206088453-2d83bb85-4a2b-417f-8ab3-47bc8f5b783f.png)
I'm thinking of getting the closest Node along the Y-axis. Is it possible? Can give me a hint? 
Thank you very much!!!

**Comment by donmccurdy** [comment]
Hi! I don't think the pathfinding library has a method to do that. You may need to do a raycast (with THREE.Raycaster) downward, and then select a Node from there.

**Comment by tranhogdiep** [comment]
So sorry, I forgot to reply to you. It works very well. Thank you so much.
