### ISSUE TITLE
Update SphereGeometry and BoxGeometry

### ISSUE THREAD

**Issue by RobinLasserye** [donmccurdy/three-pathfinding#183]
Hi,

The package is not up to date about three.js, SphereBufferGeometry need to be change to SphereGeometry, same for BoxBufferGeometry to BoxGeometry.
Otherwise, it generates a lot of warnings especially during dynamic pathfinding generation.

I could be usefull too to add a clear() option on Pathfinding and PathfindingHelper to be sure that the path is not keep in memory, for now I use reset but I'm not sure that is sufficient.

Have a good day

**Comment by donmccurdy** [comment]
Hi, thanks @RobinLasserye! You're right, things are out of date with the latest three.js versions. I think adding clear() (or maybe `.dispose()`?) methods would be a good call as well. I'm not actively working on this project right now, but would be glad to review any PRs.

**Comment by soelen** [comment]
https://github.com/donmccurdy/three-pathfinding/pull/184

**Comment by donmccurdy** [comment]
- Fixed by #184, thanks @soelen!
