### ISSUE TITLE
How to use this library react js?

### ISSUE THREAD

**Issue by natheeshsunway** [donmccurdy/three-pathfinding#205]
I am using @react-three/fiber, Is it possible to use this library  in react? If possible can you explain how ti implement this? Thank you,

@donmccurdy

**Comment by donmccurdy** [comment]
Hi @natheeshsunway! There's no React-specific anything in this library, so I'm not sure I can help with that question. The R3F Discord might be a good place to get help: https://discord.com/invite/poimandres

**Comment by natheeshsunway** [comment]
Thanks for replying @donmccurdy , So this library is not usable in react-three/fiber right?

**Comment by donmccurdy** [comment]
Any framework-agnostic JavaScript library, like this one, can be used in react-three/fiber. But I can't demonstrate for you how you would integrate a framework-agnostic Javascript library into React, Vue, Solid.js, etc., that is probably better asked in a forum with react-three/fiber users present.

**Comment by natheeshsunway** [comment]
Ok... thank you
