### ISSUE TITLE
Modify the style of generated routes

### ISSUE THREAD

**Issue by houjunlong666** [donmccurdy/three-pathfinding#234]
您好，请问改如何修改生成的路径的样式呢，我在PathfindingHelper.js这个文件里面修改了下图并没有生效
<img width="618" alt="屏幕截图 2024-03-18 214649" src="https://github.com/donmccurdy/three-pathfinding/assets/121373398/9dfd24ce-db49-4dc9-89ca-9149863d0f25">

**Comment by donmccurdy** [comment]
Hi! Note that [linewidth is ignored](https://threejs.org/docs/?q=linebasic#api/en/materials/LineBasicMaterial.linewidth) on many devices. You may need to use other types of line rendering, like the [three.js fat lines example](https://threejs.org/examples/?q=line#webgl_lines_fat). PathfindingHelper doesn't provide much customization or style, so I'd recommend copy/pasting it and changing whatever you need. :)
