### ISSUE TITLE
Lookup for dynamic obstacles

### ISSUE THREAD

**Issue by FrameMuse** [donmccurdy/three-pathfinding#246]
I've read numerous posts about dynamic obstacles, they all are either about Unity, Godot or Unreal Engine.
There were some with pure mathematics, but I'm weak in that.

Could you help me to understand how I can take into account objects when doing a path finding?

And I would like to highlight that this is not a way for me to create many navmeshes since those "obstacles" could be at any position on the map and move randomly.

**Comment by donmccurdy** [comment]
You may want to consider options like https://github.com/isaac-mason/recast-navigation-js. I'm not sure, but I suspect that these game engines may have Recast/Detour (or a similar library) built in.  three-pathfinding library doesn't deal with dynamic obstacles, and I don't have plans to expand its scope that much, Recast/Detour is a much larger and more complete system if you need those features.
