### ISSUE TITLE
The first parameter of clampStep is unused

### ISSUE THREAD

**Issue by brianpeiris** [donmccurdy/three-pathfinding#28]
The `start` parameter is unused in the implementation. It's just a bit confusing as a user. https://github.com/donmccurdy/three-pathfinding/blob/v0.9.0/src/index.js#L214

**Comment by donmccurdy** [comment]
Heh, good point, I think it was used in the past.. conceptually the parameter makes sense in terms of a step from A to B, and it may be needed to handle some edge cases, so I’d just as soon keep it.

**Comment by donmccurdy** [comment]
Closing as "wontfix" because I do want users to think of this method as clamping a step from Point A to Point B, even if that isn't technically how it's currently implemented.
