### ISSUE TITLE
4 neighbours?

### ISSUE THREAD

**Issue by Glidias** [donmccurdy/three-pathfinding#30]
buildPolygonNeighbours() appears to create quite a lot of polygon nodes with 4 neighbours. How is this possible since only a triangle has 3 sides?

Ok, after some tracing, it looks like you forgot to exclude "self" polygon from the collected set of  intersections. (Intuitively, i suspected this.).

Correction:
```
 groupA.forEach((candidate) => {
      if (navigationMesh.polygons[candidate] === polygon) return;
      if (groupB.has(candidate) || groupC.has(candidate)) {
        neighbors.add(navigationMesh.polygons[candidate]);
      }
    });
    groupB.forEach((candidate) => {
      if (navigationMesh.polygons[candidate] === polygon) return;
      if (groupC.has(candidate)) {
        neighbors.add(navigationMesh.polygons[candidate]);
      }
    });
```

**Comment by donmccurdy** [comment]
Thanks, yes that looks like a bug. :) Would you be interested in opening a PR?

**Comment by donmccurdy** [comment]
Thank you! :)
