### ISSUE TITLE
bundle.js not found

### ISSUE THREAD

**Issue by sandipJava** [donmccurdy/three-pathfinding#4]
<script src="../bundle.js"></script> in demo.html not found

**Comment by donmccurdy** [comment]
I'll add some documentation, but in short the steps to run a demo locally are (on command line in the project directory) —

```
npm install 
npm run dev
```

Then open http://localhost:9966/demo/demo.html

**Comment by donmccurdy** [comment]
Added docs for running locally, and `dist/` files that can be used without npm.
