### ISSUE TITLE
Not the shortest path

### ISSUE THREAD

**Issue by AILHC** [donmccurdy/three-pathfinding#40]
![image](https://user-images.githubusercontent.com/21373809/54585955-8295a980-4a56-11e9-9335-09117ce1f9c8.png)

**Comment by AILHC** [comment]
I don't know why
I'm New At This

**Comment by AILHC** [comment]
@donmccurdy

**Comment by donmccurdy** [comment]
This library cannot guarantee the shortest path, although for a good navigation mesh it should do very well. The issue appears when there are a mix of very large, small, and/or thin triangles in the mesh. The A* algorithms works by traversing polygon centers and then "pulling the rope" to shorten the path as much as possible. But that shortening step can't move the path to the other side of an obstacle as you show above. This approach is common in games.

From [pathfinding like a king](https://medium.com/ironequal/pathfinding-like-a-king-part-1-3013ea2c099):

> This shows us one important thing about A*, it’s a heuristic algorithm. Meaning that it will return a feasible solution in the shortest time possible, but it may not be the best solution, nor the more optimal or “natural” one.
> 
> That’s why it’s used in video games, where the perfect precision is most of the time less important than a balance between computing time and usable result. 

And from [A* pathfinding project]():

> Navmesh graphs can sometimes give suboptimal paths. This is because pathfinding is carried out on node (triangle) centers. It happens mostly when the navmesh has very large and very small nodes (triangles) placed close to each other. The pathfinding then usually prefers the path with smaller triangles (sometimes the one with larger triangles, but not as common).

> ![navmesh_suboptimal](https://user-images.githubusercontent.com/1848368/54637147-3130ee80-4a45-11e9-9a2a-324a589bd2d4.png)


> In the above image, the found path is shown in green, the nodes it passes through in pale orange. The actual shortest path is shown in red, with the nodes it passes through in pale red.
> 
> There is no silver bullet for this. Try to avoid very large triangles close to small ones.
