### ISSUE TITLE
I suggest adding save and load functions.

### ISSUE THREAD

**Issue by dytmh** [donmccurdy/three-pathfinding#47]
I suggest adding save and load functions.

**Comment by donmccurdy** [comment]
Could you share more information about what these functions should do, why they'd be helpful, and perhaps what your use case is?

/cc @mqp

**Comment by donmccurdy** [comment]
At this point I don't think I want to introduce input/output features based on the custom navmesh structure used in this project. In the future I'd love to get Detour running in WASM, which has a better way of serializing navmeshes, but that is a larger project.
