### ISSUE TITLE
Remove the need for a global THREE Object

### ISSUE THREAD

**Issue by weiserhei** [donmccurdy/three-pathfinding#49]
Is it possible to remove the need for a global `THREE`-Object, now that there are threejs modules?

Readme:
``` 
// For ES6, see: https://github.com/mrdoob/three.js/issues/9562
// CommonJS
const THREE = window.THREE = require('three');
``` 

My usecase is when I import Pathfinding from npm in my project I have to provide THREE globally. Maybe this could be done more elgeant?

**Comment by donmccurdy** [comment]
I think this could be done with an external dependency – see microbundle's `--external` flag. Unfortunately I don't have time to work on that change right now, but a PR would be welcome.

**Comment by AndrewKralovec** [comment]
Attaching this to the window & to the gloabl object did not work for me using webpack & npm modules. 
Any other solutions ?

```
const THREE = window.THREE = require('three'); // Not working
const THREE = (global.THREE = require('three')) // Not working
```

**Comment by donmccurdy** [comment]
Not sure if using Browserify counts as an "other solution", but that does work, and alternative Webpack configs may help too.

I have ideas how this could be fixed (see above) but unfortunately I'm not sure when I'll have time to do so myself.

**Comment by AndrewKralovec** [comment]
@donmccurdy , Is switching the project blunder to webpack out of the question? By using [externals](https://webpack.js.org/configuration/externals/), import statements could be used in the code, while the THREE.js module would be loaded from the cdn.



https://webpack.js.org/configuration/externals/

**Comment by donmccurdy** [comment]
I'm afraid I'd rather not use Webpack – I have a lot of repositories to maintain, and nearly all are based on Rollup, Microbundle, or Browserify. I do think Rollup and Microbundle support externals, though, if that would work.

**Comment by donmccurdy** [comment]
There's a proposed fix for this in https://github.com/donmccurdy/three-pathfinding/pull/62, by @soelen. Feedback welcome!

**Comment by donmccurdy** [comment]
Fixed in https://github.com/donmccurdy/three-pathfinding/pull/62.
