### ISSUE TITLE
How can I debug three-pathfinding?

### ISSUE THREAD

**Issue by jacklaplante** [donmccurdy/three-pathfinding#54]
Hi! I'm having an issue when I use three-pathfinding where my character that is following the path on the NavMesh will get stuck and "lose it's connection" to the nav mesh, such that it gets itself to a point where it can't find any more paths on the nav mesh. I'm not sure why this is happening an di really want to debug the issue but I can't because all of the scripts are minified. Is there a good way to debug? I tried cloning the repo and using the source files but I'm running into even more issues with that because of node and es6 modules.

**Comment by donmccurdy** [comment]
There are sourcemaps published along with this package that should (maybe depending on your application's build setup?) allow you to see the source code in the browser's developer tools, and step through in the debugger, even though the compiled code is used.

Is your own application minified too, or just this dependency? If you could share the project code, or a simpler blank project to reproduce the issue, that might be helpful. But I don't know the details of Webpack all that well, either. There may be a setting somewhere to enable sourcemaps?
