### ISSUE TITLE
Question: Can we use this library on "un-prepared" meshes

### ISSUE THREAD

**Issue by NicolasRannou** [donmccurdy/three-pathfinding#58]
Hello,

First of all, Great work!

I was wondering if we can also use this library on a un-prepared mesh, to find the shortest path between 2 vertices.

I didn't find any example and looking at the documentation it seems that is may not be the case.

Best,
Nicolas

**Comment by NicolasRannou** [comment]
I try to load my buffer geometry to prepare the 'zone', but I guess my mesh is too big :(

```
RangeError: Maximum call stack size exceeded
    at Set.forEach (<anonymous>)
    at r (three-pathfinding.module.js:1)
    at three-pathfinding.module.js:1
    at Set.forEach (<anonymous>)
    at r (three-pathfinding.module.js:1)
    at three-pathfinding.module.js:1
    at Set.forEach (<anonymous>)
    at r (three-pathfinding.module.js:1)
    at three-pathfinding.module.js:1
    at Set.forEach (<anonymous>)
```

I've got about 300k vertices

**Comment by NicolasRannou** [comment]
Maybe there is a way to avoid recursion (and Maximum call stack size) when `Pathfinding.createZone(geometry);` is called ?

**Comment by donmccurdy** [comment]
> I was wondering if we can also use this library on a un-prepared mesh, to find the shortest path between 2 vertices.

Yes and no... the mesh doesn't need to be generated by navmesh software — if you want to navigate on a rectangle, for example, `THREE.PlaneBufferGeometry` would work fine. However:

1. I'm not sure the pathfinding implementation is robust for arbitrary convex and concave shapes. It certainly hasn't been tested with cases that wrap around underneath an object. Might work, might not — if you find a quick fix that would enable this I'm happy to merge it, but I don't want to make major changes for that use case.
2. The library doesn't strictly guarantee a shortest path. See https://github.com/donmccurdy/three-pathfinding/issues/40#issuecomment-474551053. For meshes with evenly sized triangles (which navmesh software would produce) it should be quite close to shortest path. With a mix of large/small/stretched triangles, results may vary.

> Maybe there is a way to avoid recursion (and Maximum call stack size) when Pathfinding.createZone(geometry); is called ?

I'm open to PRs, but probably won't get to this change myself.
