### ISSUE TITLE
A little detour

### ISSUE THREAD

**Issue by wamwx2** [donmccurdy/three-pathfinding#59]
![QQ截图20200222031048](https://user-images.githubusercontent.com/18331515/75064301-a2183a80-5521-11ea-8ad0-3c77b98a8dfd.png)
![QQ截图20200222031105](https://user-images.githubusercontent.com/18331515/75064304-a3496780-5521-11ea-9245-28d1a88ce7a5.png)

**Comment by donmccurdy** [comment]
Can you share a demo, or the navmesh? Or enable wireframe mode in your screenshot to debug?

This navmesh algorithm does not guarantee a shortest path in all cases, but it should give pretty good results when the navmesh has consistently sized triangles. If there are long/thin triangles in the mesh, you can get weird results. See: https://github.com/donmccurdy/three-pathfinding/issues/40.

**Comment by wamwx2** [comment]
Thank you very much for your answer.

The problem may be the same as # 40.
The pictures below hope you can help.
![QQ截图20200222164727](https://user-images.githubusercontent.com/18331515/75089437-b4cb5780-5593-11ea-8e3b-db451d4cdd69.png)
![QQ截图20200222164741](https://user-images.githubusercontent.com/18331515/75089438-b6951b00-5593-11ea-9b97-0b8ae74d68ae.png)
![QQ截图20200222154926](https://user-images.githubusercontent.com/18331515/75089439-b85ede80-5593-11ea-91ae-a8aea6bb83b5.png)

**Comment by donmccurdy** [comment]
I believe it's the same issue, and the easiest way to confirm that is to try with a mesh that has consistent triangle sizes. Can you test with this version of the navmesh? You may need to set `material.side = THREE.DoubleSide` to see it.

[Archive.zip](https://github.com/donmccurdy/three-pathfinding/files/4239777/Archive.zip)


- Left: After
- Right: Before

![Screen Shot 2020-02-22 at 10 33 54 AM](https://user-images.githubusercontent.com/1848368/75097413-656b3400-555f-11ea-8e72-5bde0ca07ffc.png)

**Comment by wamwx2** [comment]
The problem is solved! Thank you very much for your ideas.

I redesigned NavMesh again. For the final result, please see the picture

![未标题-1](https://user-images.githubusercontent.com/18331515/75131497-4eb70f80-570e-11ea-9196-7fac7dc0ff52.jpg)
