### ISSUE TITLE
How to implement a joystick in the game?

### ISSUE THREAD

**Issue by wamwx2** [donmccurdy/three-pathfinding#60]
Hi Don

When we hit the wall with the joystick in the game, the character does not stop immediately, but moves against the wall.
How should it be achieved?

E.g:

![王者荣耀_2020-02-24-22-45-19_2_2](https://user-images.githubusercontent.com/18331515/75163819-d32f7f80-575a-11ea-928a-f9a41582a017.gif)
![王者荣耀_2020-02-24-22-45-19_1_1](https://user-images.githubusercontent.com/18331515/75165411-4f2ac700-575d-11ea-99d5-1e25b51171c0.gif)

**Comment by donmccurdy** [comment]
The `clampStep` method is meant to help with this. Pass in the vector your character would normally move during a frame, and it will return a vector adjusted for moving against the wall, if a wall is in the way: https://github.com/donmccurdy/three-pathfinding#clampstep
