### ISSUE TITLE
can't open the link in readme.md

### ISSUE THREAD

**Issue by JulianGuSM** [donmccurdy/three-pathfinding#7]
this link i can't open (https://medium.com/@donmccurdy/creating-a-nav-mesh-for-a-webvr-scene-b3fdb6bed918)
i try to pin https://medium.com ,i got that can't find mainframe

**Comment by donmccurdy** [comment]
By "i got that can't find mainframe" do you mean you aren't able to open https://medium.com either?  

Perhaps the site was temporarily down, or maybe this is a regional issue... is it still not working now?

**Comment by JulianGuSM** [comment]
Yes, i still can't open the https://medium.com.
Maybe this is regional issue.
The website teach us how to create a navigation mesh using Blender,i will try another website in  PatrolJS to learn how to create a navigation mesh using Blender.
Thanks a lot!

**Comment by donmccurdy** [comment]
Sorry about that :/ 

Are you able to open my website (https://www.donmccurdy.com/) ? I could try re-posting the article there.

**Comment by JulianGuSM** [comment]
Oh,i can open the website (https://www.donmccurdy.com/),thanks a lot! :)

**Comment by donmccurdy** [comment]
Great, here's an updated link to the article: https://www.donmccurdy.com/2017/08/20/creating-a-nav-mesh-for-a-webvr-scene/ 🙂

**Comment by JulianGuSM** [comment]
Yeah，thank you so much ：）
