### ISSUE TITLE
Remove dist/ folder

### ISSUE THREAD

**Issue by donmccurdy** [donmccurdy/three-pathfinding#73]
Including the `dist/` folder in source control is a regular source of confusion for new contributors, because the files are modified when building or testing changes, but shouldn't be included in PRs. These files cannot be reviewed easily, and are meant to be rebuilt by an author when publishing a new release. To avoid this confusion, the `dist/` folder should be added to `.gitignore` and explicitly added to the published files in `package.json`. Because it's published to NPM, it will still be available from CDNs like Unpkg.

**Comment by makc** [comment]
but https://github.com/donmccurdy/three-pathfinding/blob/master/demo/index.html#L8 will break on github pages

**Comment by makc** [comment]
ah https://donmccurdy.github.io/three-pathfinding/demo is 404, I guess it is forks problem then :D

**Comment by donmccurdy** [comment]
I don't use GitHub pages much anymore, the demo is at https://three-pathfinding.donmccurdy.com/demo/.
