### ISSUE TITLE
ReferenceError: THREE is not defined - bundle.js:4:1

### ISSUE THREAD

**Issue by dirkk0** [donmccurdy/three-pathfinding#8]
Hi,
after successfully installing this, running the server and navigating to :9966, I get a 
`ReferenceError: THREE is not defined - bundle.js:4:1` error on the console.

**Comment by donmccurdy** [comment]
I'll try to clean this up so something more reasonable is shown first, but note from the docs that you have to go to http://localhost:9966/demo/demo.html, not just localhost:9966

**Comment by dirkk0** [comment]
And that's what I did.
A localhost:9966 wouldn't give me a javascript error, rather an empty page.

As you mentioned in the docs it works if you include the lib from dist into your html, like so:
http://curious-electric.com/w/experiments/threejs/navmesh/

I am only saying that this doesn't:

    git clone https://github.com/donmccurdy/three-pathfinding.git
    cd three-pathfinding

    npm install
    npm run dev

**Comment by donmccurdy** [comment]
Hm, I can't reproduce the error then. I'm not copying anything from `dist` to run the demo, just the steps above. THREE isn't actually part of the build at all, it's just [required from a CDN](https://github.com/donmccurdy/three-pathfinding/blob/master/demo/demo.html#L35). Are there any network errors?

**Comment by dirkk0** [comment]
you are right, totally my fault.
