### ISSUE TITLE
Does this account for mesh position?

### ISSUE THREAD

**Issue by aunyks** [donmccurdy/three-pathfinding#82]
Hey Don! Thanks for making this. I was wondering: does this library account for mesh position somehow when returning agent paths? As in, given a geometry vertex at (0, 0, 0) and mesh position at (1, 1, 1), will the library say that this vertex is at (1, 1, 1)? Assuming that the vertex is in the path. 

I was reading some of the code, but I can’t tell for sure. I know the `Pathfinding` is only given a geometry and not the whole mesh, but I just thought I’d ask.

**Comment by donmccurdy** [comment]
Hi! I think you're asking about the navigation mesh, and not the agent mesh, correct?

The BufferGeometry used to construct the navmesh doesn't have any reference to its parent mesh (and, often, you aren't rendering the navmesh in the scene anyway). So if the scene is shifted by some offset, or maybe you have multiple navmeshes, you'd need to use that offset to translate between the local space of the navmesh and your world coordinate space.

**Comment by aunyks** [comment]
Gotcha! Yes, I was referring to the navmesh. Thanks for your help.
